# Generated by Django 3.2.9 on 2021-11-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0002_alter_book_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerName', models.CharField(blank=True, default='', max_length=100)),
                ('bookId', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='created',
        ),
    ]
