# Generated by Django 3.2.9 on 2021-11-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('fiction', 'Set in a fictional universe'), ('non-ficiton', 'Set within our universe')], default='fiction', max_length=100),
        ),
    ]
